### ISSUE TITLE
Checklist template Design Form

### ISSUE THREAD

**Issue by abachman** [rubyforgood/voices-of-consent#13]
CoreBoxItems index. 

Follow pattern from BoxDesign Form. 

CoreBoxItem == many-to-many AbuseType/InventoryType

**Comment by maebeale** [comment]
Step 1: UI
- By associating AbuseTypes with InventoryTypes here, Admins can adjust which BoxItems will be added by default at the BoxDesign phase.

Step 2: Implementation
- Add method to aasm state design_in_progress (in Box) to auto-create relevant BoxItems per associated AbuseTypes (found in Box#tag_list)
