### ISSUE TITLE
box design `mark_as_designed` should take box id param

### ISSUE THREAD

**Issue by abachman** [rubyforgood/voices-of-consent#133]
needs to be more limited than just designed_by

**Comment by maebeale** [comment]
Right now http://localhost:3000/box_design/new seems to be a design for the last box the user was assigned to, but it probably should require a box_id url param so we can mark the relevant box as designed (e.g. /boxes/:box_id/design)

**Comment by maebeale** [comment]
Fixed via: https://github.com/rubyforgood/voices-of-consent/pull/278
