### ISSUE TITLE
Improve styling of navbar

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#150]
We'd like to make the navbar look like the photo below (there will be more icons added later, so there should be room for those)
- needs text at bottom
- logo should be fixed at left
- add padding and/or shrink icons
- add user info (w default icon if no photo) per design

![Nav bar only- VOC](https://user-images.githubusercontent.com/7607813/62584551-286d7780-b883-11e9-9f7e-ec210a84cb9c.jpg)

**Comment by abachman** [comment]
![image](https://user-images.githubusercontent.com/13002/62986045-e48cec00-be07-11e9-9ac4-3794c80f9180.png)

Probably about as close as I can get.

**Comment by abachman** [comment]
PR #165 is ready to go.
