### ISSUE TITLE
Make navbar icons actual links

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#159]
- home should go to root_path

- the icon buttons should all go to box_requests_path, but with varying filters already applied

- status icon should go to box_requests_path
- review icon should go to box_requests_path for box_requests that don't have any associated boxes (needs a scope on box_request model) and reviewed_by_id is EITHER current_user.id or nil
- design icon should go to box_requests_path for box_requests where designed_by_id is EITHER current_user.id or nil, so could be those assigned to "me" or those that need to be claimed (needs a scope on box_request model)
- package icon should go to box_requests_path for box_requests where packaged_by_id is EITHER current_user.id or nil(needs a scope on box_request model)
- shipping icon should go to box_requests_path for box_requests where shipped_by_id  is EITHER current_user.id or nil (needs a scope on box_request model)

![Nav bar only- VOC](https://user-images.githubusercontent.com/7607813/62584805-117b5500-b884-11e9-9aa0-21128cae8689.jpg)

**Comment by MxOliver** [comment]
I'll take this

**Comment by maebeale** [comment]
awesome, @MxOliver ! i've got one related commit that might help too. will push now.

**Comment by maebeale** [comment]
@MxOliver Updated! #160 created the groundwork for you to have places for those icons to link to!
https://github.com/rubyforgood/voices-of-consent/pull/207. I think the rest of the aasm work you did handles the conditions above?

**Comment by MxOliver** [comment]
The aasm should handle all those concerns, if the condition doesn't pass where should I route the icon to? Like for the review icon, if the box does have an associated box what path should it go?

**Comment by maebeale** [comment]
TOTALLY open to your suggestions here. I'm thinking that the Review link
should go to:
box_requests?filter_by=review_in_progress&reviewer_id=current_user.id

So, the Review button is really taking you to "My Reviews in Progress".

For the above, we'd need to add reviewer_id as a param/scope on BoxRequest
model and implement in the controller.

Also, the Review link should only be available to users with
user.permissions.include?(Permission::REQUEST_REVIEWER)

Does that approach sound good to you?

**Comment by MxOliver** [comment]
I am struggling with this one, my erb template skills are lacking especially for path filtering. If someone with more erb experience would like to pair with me on this I'd be happy to help, or I can also just release it back into the wild to be claimed by someone else

**Comment by sarslanoglu** [comment]
@MxOliver I can work on this one with you. Where do you block on?

**Comment by MxOliver** [comment]
Yeah you can absolutely take over this one!

**Comment by maebeale** [comment]
Sorry I missed your comment here earlier, @MxOliver ! Thanks for jumping in @sarslanoglu !
We've started to implement this in the dropdown on box_requests index, so maybe that could be referenced for the button code to get y'all further?

**Comment by maebeale** [comment]
@sarslanoglu, hello! what's the latest on this issue?

**Comment by sarslanoglu** [comment]
@maebeale Omg completely forgot this issue, working on it asap. It will be ready to review tomorrow
