### ISSUE TITLE
Footer is displaying in the middle of /box_requests index

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#161]
- change footer ("copyright ... ") so it's always at the bottom

![Screen Shot 2019-08-06 at 8 51 24 PM](https://user-images.githubusercontent.com/7607813/62586528-0d533580-b88c-11e9-8789-ac808044a87d.png)

**Comment by conj40** [comment]
Hi, has this been resolved? I have just tested on my local machine and cannot reproduce

**Comment by maebeale** [comment]
hello there, @Chub93! it hasn't been resolved. it might require creating a bunch of box_request seeds to see it?

**Comment by conj40** [comment]
Ah yes, I am able to reproduce now, thank you! I will get this fixed for you.
