### ISSUE TITLE
Remove `inventory_adjustment_id` from box_items table

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#166]
(InventoryAdjustment belongs_to :box_item, so the field isn't needed on box_items table)
- Remove it from any views, strong params, etc, too

**Comment by AlexAvlonitis** [comment]
Hi, can i get this one?

**Comment by maebeale** [comment]
Sure can! Thanks, @AlexAvlonitis

**Comment by AlexAvlonitis** [comment]
I think this has been done before: https://github.com/rubyforgood/voices-of-consent/blob/develop/db/migrate/20190807023956_change_box_item_inventory_adjustment_to_item_type.rb

Also can't seem to find box_item -> inventory_adjustment references anywhere, only the other way around (inventory_adjustment -> box_item

**Comment by maebeale** [comment]
@AlexAvlonitis you're right! thank you!
