### ISSUE TITLE
Get tests green again

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#167]

**Comment by MxOliver** [comment]
Was looking into this, and from what I can tell all failing controller tests have the same issue in common which is the valid_session on get new. I don't know much about using session in rspec but it seems in every test on the /new route, it's being redirected to user/sign_in and authentication is failing. 

It's line 61 in pretty much ever controller test except box_assembly_controller_spec which is line 6

The model test that is failing, box_request_spec, it looks like adding the tag to tag_list will add it to both  box_request.tag_list and box_request.tags, but removing a tag only removes it from box_request.tag_list but it is still in box_request.tags

**Comment by katestud** [comment]
👋 Hi there! First time contributor here. This issue seemed like a good place to start getting familiar with the codebase, so I started taking a whack at this and got pretty far. I'd be happy to open a PR in the next day or two that addresses most failing test cases if it's helpful, but I don't want to step on anyone's toes.

**Comment by maebeale** [comment]
👋 Hi, @katestud! So glad to have your help!!! 

@bransynluther is assigned to this and has been working on it as well (as have I). We've been working in the `fix-more-tests` branch, where it'd be awesome to merge your work. I'd planned to be working on this tonight actually. No toes here -- especially on this branch. We're really wanting to get our tests working again so others can onboard easily and we all can rest a little easier! :)

@bransynluther would you make sure your latest is committed to the branch and pushed to gh?

**Comment by bransynluther** [comment]
Rodger that!

**Comment by katestud** [comment]
Woo! I've got a branch in progress here: https://github.com/katestud/voices-of-consent/tree/fix-more-tests. I had to make some adjustments since the base was a bit different from the `develop` branch I was originally working off of, but I can open a PR against the `fix-more-tests` branch with what I have if it would be helpful! ❤️

**Comment by maebeale** [comment]
Hey! Sorry about that. Yes! That'd be amazing!!! Thank you!
