### ISSUE TITLE
Add state machine methods to determine current and next stages

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#172]
BoxRequests go through the following stages:

- `requested` when `box_request.reviewed_by_id == nil`
- `review_in_progress` when `box_request.reviewed_by_id != nil`
- `reviewed` when `box_request.reviewed_at != nil`
- `design_in_progress` when `box.designed_by_id != nil  && box.designed_at == nil`
- `designed` when `box.designed_at != nil && box.assembled_by_id == nil`
- `assembly_in_progress` when`box.assembled_by_id != nil`
- `assembled` when `box.box_items.pluck(:included).all?`
- `shipping_in_progress` when a `shipped_by_id != nil && shipped_at == nil`
- `shipped` when a `shipped_at != nil && [no associated Message exists (w subject line "follow-up"???]`

- box_request `needs_review?` when created with no reviewed_by_id
- box_request is `needs_design?` when a reviewed_by_id exists, and an associated box exists with no designed_by_id
- box_request is `needs_assembly?` when a designed_by_id exists, but no assembled_by_id exists
- box_request is `in_assembly?` when a assembled_by_id exists, but no shipped_by_id exists
- box_request is `in_shipping?` when a shipped_by_id exists, but no shipped_at exists
- box_request is `in_followup?` when a shipped_at exists, but no associated Message exists (w subject line "follow-up"???)

**Comment by MxOliver** [comment]
Can I work on this?

**Comment by maebeale** [comment]
@MxOliver hey! i've got some code written for it. will assign myself for now, and can push what i have by tomorrow (in meetings all afternoon/evening today). does that mess up your plans for today?

**Comment by MxOliver** [comment]
No that works out, I worked on it earlier but I'm not planning on pushing anything today so just let me know when you merge and I'll just pull in your changes into my local branch and keep going

**Comment by maebeale** [comment]
i doubt whatever i had will be conflicting. my vote is for you to press on! sounds like you've got it well underway based on the questions, so, that's awesome! :)

**Comment by MxOliver** [comment]
I added migrations with the missing fields (designed_at, etc) should i make a separate PR for that or keep them together? (my thought is to keep them together because the state machines won't work without them because of the guards set up)
