### ISSUE TITLE
Adjust contact consent radio buttons on BoxRequest form

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#173]
add "ok_to_email" under email and "ok_to_mail" the same way as the phone field radio buttons

also, for all of these radio buttons, make sure all of them are required fields

**Comment by MxOliver** [comment]
I'd like to work on this

**Comment by maebeale** [comment]
Great! Thank you!

**Comment by MxOliver** [comment]
I think this is already done?

**Comment by jenpen** [comment]
I believe this was closed by https://github.com/rubyforgood/voices-of-consent/pull/198
