### ISSUE TITLE
MessageLog needs more fields

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#176]
MessageLog needs:

- `subject_line` so we can better log messages sent out
- `message_type` so we can track when follow-up stage is completed (Type examples include: followup_email)
- `message_channel` (e.g. `autoemail, email, text, call, mail`)

Please find where we are creating MessageLogs and update those to populate the fields above.

**Comment by MxOliver** [comment]
Submitting a PR with these new migrations now
