### ISSUE TITLE
Improve Box Design UI by adding type-ahead and/or reference list of InventoryTypes

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#213]
- Right now the user needs to remember the Inventory Types and search
- A type-ahead here showing all Inventory Types could be a HUGE help
- Bonus if the list is only showing types not already associated to this Box, and the list updates itself after any item is selected
- We like being able to add any item here that's not already an inventory item, but do want to be drawing from the Inventory Types list to start

**Comment by smoline** [comment]
I would like to work on this one.

**Comment by maebeale** [comment]
Awesome, @smoline !
