### ISSUE TITLE
Improve BoxRequest Review (box_requests/:id/edit) UI

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#224]
- The white background isn't expanding based on the column content
- This issue can be recreated by filling out a new form via `/requesters/new` and add multiple paragraphs for the text fields, and then going to that BoxRequest's Edit route

**Comment by skrishna243** [comment]
Can you please assign this to me?

**Comment by maebeale** [comment]
It's yours! Thank you!
