### ISSUE TITLE
Replace hard-coded abuse types on the form

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#238]
In our public-facing form (app/javascript/src/components/box-request-form), we're hard-coding abuse types:
- We'd like to replace the hard-coded list in the form with a call to the data in the abuse_types table so users can add abuse types to the form without calling a developer.

**Comment by gkpacker** [comment]
I'd like to work on this issue!

**Comment by maebeale** [comment]
Thanks, @gkpacker !

**Comment by gkpacker** [comment]
Where can i make a feature spec for it?

**Comment by maebeale** [comment]
@gkpacker we don't have any feature specs yet, so this is very exciting (and relieving!)!
we *do* have capybara installed already, and we are using rspec. if you would create a new dir `features` under `spec` and put the file in there, that'd be perfect.

**Comment by gkpacker** [comment]
Ok, thanks! I'll open the PR soon
