### ISSUE TITLE
Add link to README.rb to CONTRIBUTING.rb

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#239]
Add link to: https://github.com/rubyforgood/voices-of-consent/blob/develop/CONTRIBUTING.md on the README

**Comment by abhushanaj** [comment]
Can I do this? I am learning Open Source and I guess I can do this succesfully.

**Comment by shaunakpp** [comment]
Hi @maebeale, I just noticed this issue while browsing for Hacktoberfest issues, and sent a pull-request. Thank you for opening up voices-of-consent for Hacktoberfest! Happy hacking!

**Comment by FriendBesto** [comment]
heh, oops... guess we both had the same idea
