### ISSUE TITLE
Update Devise to handle GitHub alert re gem vulnerabilities

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#240]
https://github.com/rubyforgood/voices-of-consent/network/alerts

**Comment by z3ugma** [comment]
@maebeale I get a 404 from that URL, possibly because I'm not a maintainer. Can you paste the raw alerts in the issue?

**Comment by maebeale** [comment]
![Screen Shot 2019-10-13 at 11 08 16 PM](https://user-images.githubusercontent.com/7607813/66771441-3db8e080-ee88-11e9-9a3d-8927f0491d0b.png)

**Comment by maebeale** [comment]
@z3ugma 

![Screen Shot 2019-10-14 at 1 40 31 PM](https://user-images.githubusercontent.com/7607813/66771454-490c0c00-ee88-11e9-8991-dc0a7c9c9499.png)
