### ISSUE TITLE
Change button text on BoxRequest form

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#242]
Add text to the submit button on BoxRequest form.

Instead of the default, we'd like it to say: "Complete Box Review" so it's more clear that BoxRequest create completes one of the Box lifecycle phases.

**Comment by shaunakpp** [comment]
Hi @maebeale, Is it okay if I pick this up?

**Comment by maebeale** [comment]
Sure is, @shaunakpp ! Please make sure to check if there's a test that relies on the button text (I don't think there is, and if there's not, would you be willing to add one as part of the PR?).

**Comment by shaunakpp** [comment]
Hi @maebeale, I've created a draft pull request https://github.com/rubyforgood/voices-of-consent/pull/276 for this issue, but I noticed that there is a component for BoxRequest form which has a submit button value "SUBMIT - SEND ME A SURVIVOR BOX". Do I need to change that too? Or Am I misreading it completely 😅 ?

**Comment by maebeale** [comment]
hey there! nope, that "send me a survivor box" button is different. we only need to change the text on the Rails side.

**Comment by maebeale** [comment]
Would it be possible to change the test to `edit` instead of for `new`?
(We won't be creating any BoxRequests through the admin side. They will all come in through the `/requesters/new` form.

**Comment by shaunakpp** [comment]
Hi, I've added specs to check the submit button value for `edit` and also kept the specs for `new`. I can add a few more tests for edit(like checking requester and other elements getting rendered correctly) in a separate pull-request, is that okay?

**Comment by maebeale** [comment]
That's GREAT, @shaunakpp ! Thanks!
