### ISSUE TITLE
Change styling of user button in nav

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#257]
- add user info (w default icon if no photo) per design
- we'd like it to match the following design

![navbar](https://user-images.githubusercontent.com/7607813/66577397-4e471f00-eb47-11e9-9fd3-902b705699ba.jpg)

**Comment by sarslanoglu** [comment]
I can work on this issue, if it is still available @maebeale

**Comment by maebeale** [comment]
Great! Thank you, @sarslanoglu !

**Comment by sarslanoglu** [comment]
@maebeale When i looked at desired design, how could i decide user is adminisrator or just volunteer?

**Comment by maebeale** [comment]
@sarslanoglu GREAT question! If they have the Permission::MANAGE_USERS, they will be an "Administrator", otherwise, they're a "Volunteer".
