### ISSUE TITLE
Add Sendable polymorphic association to MessageLog

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#258]
- `sent_to` needs to be polymorphic so `MessageLog` reflects messages sent to either a Volunteer (via User) -OR- a Requester.
- I think it's ok to expose User names (via def name), but for the Requester, we prob should add a def name that's the request date and city, rather than show their name in the dropdown. 

Thank you for helping us build in sensitivity to people's privacy! Incredibly important.

**Comment by smoline** [comment]
I would like to work on this one!
