### ISSUE TITLE
Improve documentation: add links to database-diagram

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#260]
- Add note under Background section that mentions we have a graphviz database-diagram, so people can reference the photo (add link to png below) or visit `http://graphviz.it/` and paste the code from the .dot file to see it in the browser (and generate new versions of .png or .dot as needed). Might want to add a note that you need to delete the code that's in the website first and then paste over it entirely. 
- Add link under the Background section on README to link to the database-diagram.png
- Add link under the Background section on README to link to the database-diagram.dot
- Add link to Casey Watts' instructional post re graphviz, `https://gist.github.com/caseywatts/be69bf941fa1f8e264bd07de698366a0`

**Comment by smoline** [comment]
I would like to work on this one.
