### ISSUE TITLE
Fix bug that occurs when creating new Volunteer

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#271]
- Getting a primary key validation error when creating a new Volunteer 
- Reproduce by visiting `/volunteers/new`, filling out the form, and clicking create at bottom

**Comment by steph-hickman9** [comment]
@maebeale  

I want to support what this project is doing, it is such important work! 

I found that the application references volunteer.user_id, when we should really be referencing volunteer.user.id. I was able to to switch these and in my local environment, and now I can create new volunteers. Is there anything else I should do before making a pull request?

**Comment by maebeale** [comment]
Thank you, @steph-hickman9 !!! Yes, we think so too.

Excellent! Yes, there was an old assumption that Volunteer would belong to User, but it's not that way anymore. Great catch!

If you could add a test confirming what you've changed, that'd be fantastic!

**Comment by maebeale** [comment]
(lmk if you need help on this, @steph-hickman9!)
