### ISSUE TITLE
Test suite help!

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#272]
We started this application during a hack weekend, and haven't been able to wrangle our test suite back to green yet. ANY help on this is VERY much appreciated!!! Even if you submit something to make ONE test pass, we'd be grateful.

**Comment by Saroj-maker** [comment]
Just be calm and say all is well and try to find out the way by yourself.

**Comment by bethurban** [comment]
I'll take a look!

**Comment by maebeale** [comment]
Thank you, @bethurban ! :)

**Comment by cassianoblonski** [comment]
i'm fixing some specs

**Comment by maebeale** [comment]
Great, @cassianoblonski ! I just merged some code people had worked on re tests too, so you might want to update develop and merge them in. All help welcomed here!

**Comment by jon-flores** [comment]
Hi I took a stab at some spec updates. I'll look into more when I can. 
Thanks for the opportunity!

**Comment by maebeale** [comment]
Thanks, @jon-flores!

**Comment by atzorvas** [comment]
Took the will to kill 'em 🙃 - relevant PR #320
