### ISSUE TITLE
Add more tables to db/seeds/dev.rb

### ISSUE THREAD

**Issue by z3ugma** [rubyforgood/voices-of-consent#274]
#261 seeks development seed data
#273 adds some seed data

Add seed data for dev for additional tables like `Requester` and `BoxRequest`

**Comment by matisnape** [comment]
Can I take this? :)

**Comment by maebeale** [comment]
Sure can, @matisnape !

Feel free to add any seeds to any and all tables! 

I'm going to make another issue with some specific seed data we need, so feel free to claim that one after, if it interests you!

**Comment by matisnape** [comment]
@maebeale does CRUD for those things work locally? I see a lot of frontend errors in console when creating requester via /requesters/new and I get 422 from backend

EDIT: found it, there's a backend validation for phone number in format xxx-xxx-xxxx which is not displayed on submit 🙄

**Comment by maebeale** [comment]
Reopening this issue because we need some seeds for message logs that correspond with the Box request and Box seeds created

**Comment by maebeale** [comment]
Also need seeds for storage_unit Locations and inventory_tallies

**Comment by maebeale** [comment]
And any other tables.

**Comment by maebeale** [comment]
When committing re this issue, please list it as `partially resolves #274` so it can stay open

**Comment by mauricio-prl** [comment]
can I try to do the message logs seeds?

**Comment by maebeale** [comment]
Yes please, @m-pereira !
