### ISSUE TITLE
Add icons to /box_requests to indicate when a phase has been completed

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#280]
- We'd like to replace the text in brackets on /box_requests index with check mark icons (a la font-awesome or bootstrap icons). 
- Ideally they'd be grey in color to match the color scheme

![Screen Shot 2019-10-10 at 7 06 46 PM](https://user-images.githubusercontent.com/7607813/66612979-d520e980-eb91-11e9-943b-025536152541.png)

**Comment by Sommerariel** [comment]
Hey @maebeale I would love to help! Can I take this issue?

**Comment by kalpananegi** [comment]
May I?

**Comment by shaunakpp** [comment]
Hi @maebeale, I looked this up, and most of the changes were already in place,  we just needed to add `fontawesome` and modify the class name in `index`. I've sent this pull-request: #286
