### ISSUE TITLE
BoxDesign draws InventoryTypes from the database

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#288]
- Right now the InventoryTypes are hard-coded

**Comment by z3ugma** [comment]
I'm interested in this one

**Comment by z3ugma** [comment]
So it looks like `app/javascript/src/components/box-design-form/BoxDesignForm.jsx:6`
has the line:
`import { itemTypes as mockItemTypes } from '../../mocks/mockData';`

Which has:
```
export const itemTypes = [
    'Toothbrush',
    'Soap',
    'Glitter',
    'Bath Bomb',
    'Shoes',
    'Socks',
    'Silverware',
    'TV',
    'Sunglasses',
    'Peanuts',
    'Hairbrush',
    'Bible',
  ];
```

What's the architecture you'd like - is it a `:json` endpoint in `app/controllers/inventory_types_controller.rb`  that returns inventory types with an AJAX call in React?

**Comment by z3ugma** [comment]
From Slack discussion:

> maebeale:
> AbuseTypes are being called in the front end on /requesters/new. Idk if it's the recommended pattern, but it's a pattern! Only thing is that we don't want to replace /index like they did in AbuseTypes, just to add a respond_to.

**Comment by maebeale** [comment]
@z3ugma is that enough to go on?

**Comment by z3ugma** [comment]
Yes, that's much clearer. You can assign me this one.
