### ISSUE TITLE
Build box request form

### ISSUE THREAD

**Issue by abachman** [rubyforgood/voices-of-consent#3]
Accept initial box request. 

See https://www.voicesofconsent.org/survivor-box for current example and the page where it will be embedded.

This is a big high level ticket.

**Comment by maebeale** [comment]
@jgaskins is a great resource for this topic

**Comment by maebeale** [comment]
Fields in data model should match what you see on the form, but some are shorthand. @abachman suggested using en.yml for full question text.

**Comment by maebeale** [comment]
Please copy styling, font, etc from the organization's website.

**Comment by maebeale** [comment]
Please check in w @jessbeach re suggested pagination

**Comment by maebeale** [comment]
Requires:
* Requester model/controller 
* BoxRequest model/controller
Once you've added these, please update the team

**Comment by bolducp** [comment]
Initial UI added in PR https://github.com/rubyforgood/voices-of-consent/pull/94

**Comment by maebeale** [comment]
@bolducp hey! on the form, may we add "ok_to_email" under email and "ok_to_mail" the same way you added those to the phone field? 

also, for all of these would you default them to "Yes" (then we'll have data even if they skip over the answer) or, make them required fields?
