### ISSUE TITLE
`researched_at` datetime added to BoxItem

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#303]
- add a `researched_at` datetime field on box_items table (we'll need a UI later for fulfilling box_item research needs that these will be useful for)
- update Box#mark_box_items_as_researched! method to also update researched_at: Time.now
- update Box#box_item_research_completed? from `research_status << box_item.researched_by_id.present? ? true : false # TODO - add researched_at to BoxItem` to `research_status << box_item.researched_by_id.present? && box_item.researched_at ? true : false`

**Comment by amyhenning** [comment]
I'll pick this one up!

**Comment by maebeale** [comment]
Great, @amyhenning !
