### ISSUE TITLE
Add block on emails being sent if Requester or Volunteer selected *not* ok_to_email

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#305]
Whenever a Mailer is called, if the person didn't "ok" an email being sent, it shouldn't get triggered.

**Comment by sarslanoglu** [comment]
I can work on this issue. What will happen if Mailer tries to email someone with ok_to_email: false person. Should it give an error or just do nothing?

**Comment by maebeale** [comment]
@sarslanoglu , great! thank you for the help! i'll assign this one to you.

Thanks for being up that failure nuance. I was going to create a follow-up issue for that, but hadn't decided what the ideal behavior should be. What do you recommend?

**Comment by sarslanoglu** [comment]
@maebeale Couldn't come with an idea. I just checked that ok_to_email on volunteer and requester. If it is set to false AutoEmailHandler will not be called at all
