### ISSUE TITLE
Need for CI and checks in PRs

### ISSUE THREAD

**Issue by atzorvas** [rubyforgood/voices-of-consent#327]
A CI with github integration in order to only allow PRs with passing tests to be merged would be greatly beneficial as a green test suite is the easiest way for someone to get quick feedback and contribute more easily and with more confidence!

I'd suggest [Gitlab CI](https://about.gitlab.com/solutions/github/) as it seems feature-proof and also acquired gemnasium - given that we have a ruby/rails project! =)

**Comment by h-m-m** [comment]
I have a slight preference for Circle CI because other Ruby for Good projects have tried using it. That said, if Gitlab CI is easier for you to set up, I'm for it!

**Comment by h-m-m** [comment]
I'm going to try and make some progress on this over the weekend. I'll let you know how it goes.

It would certainly help me feel more confident when merging in pull requests

**Comment by maebeale** [comment]
YESSS! Thanks, @h-m-m !!!
