### ISSUE TITLE
Remove duplicate LocationType field from locations#new form

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#329]
We have the select dropdown working, so don't need the integer field at the bottom.

![VoicesOfConsent](https://user-images.githubusercontent.com/7607813/66725316-b70bf100-edfe-11e9-956d-92d40d35f0dd.png)

**Comment by HenrySabio** [comment]
I'd like to claim this Issue! @maebeale 
Just to confirm the issue is located in "voices-of-consent/app/views/locations/_form.html.erb"?

**Comment by maebeale** [comment]
Thanks, @HenrySabio ! Correct! :)
