### ISSUE TITLE
inventory_tallies/_form should only show locations that are of type: "storage_unit"

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#330]
Right now the InventoryTally form shows all Locations in the database in the f.association :storage_location, and we want to have it filtered to where(location_type: "storage_unit")

**Comment by lucianolima00** [comment]
Hey @maebeale, I'd like to do this one

**Comment by maebeale** [comment]
@lucianolima00 , great! thank you!
