### ISSUE TITLE
volunteers/new form doesn't show error if county is left blank

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#332]
Other fields produce the pink error class when left blank, but for some reason the county field doesn't. You can see a JS error in console, but nothing prompts the user to know it's a required field.

**Comment by seal62** [comment]
Im happy to take a look at this. can you point me in the direction of the form in the code base.. it looks pretty extensive. thanks

**Comment by maebeale** [comment]
Thank you, @seal62 ! If you go to /views/volunteers/new, it'll show the name of the JS file where the code lives. Lmk if that's helpful enough or not!

**Comment by seal62** [comment]
Created PR https://github.com/rubyforgood/voices-of-consent/pull/350

**Comment by notapatch** [comment]
Hello @maebeale 

Reading through your issues and it looks like this has been merged but the issue has been left open.

**Comment by JoaoFernandesVale** [comment]
@maebeale this is also working for me. 
Although the error is quite vague and does not say what is the field that needs to be populated. 

Perhaps this issue could be closed and a new one created to improve  these errors.

**Comment by maebeale** [comment]
@Joao-Quaresma thank you for confirming the above!
