### ISSUE TITLE
Make a louder error on /volunteers/new and /requesters/new when invalid email is input

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#333]
We want the email field to highlight pink when there's an invalid email input. Currently it fails in the console/server but there's no feedback provided to the user.

Per @mastisnape:
Currently there's no visible validation message about required format in the app and user won't know why the submit button doesn't do anything - I only saw 422 in the logs. So basically, you need to pass the Rails validation error to the user interface via JS.

The only validation visible is if some required fields are not filled in.

**Comment by efl7a** [comment]
Could I work on this?

**Comment by maebeale** [comment]
Sure can, @efl7a ! Thank you!

**Comment by efl7a** [comment]
@maebeale - I see the email field you are referencing on requesters/new, but there is not an email  input on volunteers/new.  I will work on the requesters/new and you can tell me what you want to do re: volunteers/new.
