### ISSUE TITLE
Add ability to create a new Location from within the volunteers/new form

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#334]
Users can select from existing Universities on `/volunteers/new` form.
We'd like a select2 that allows a create (if not found using typeahead) on Location
Location needs a `location_type`, so this should be defaulted to the string `university`

**Comment by shivamvinsol** [comment]
I can have a look on this.

**Comment by maebeale** [comment]
Perfect! Thank you, @shivamvinsol!

**Comment by shivamvinsol** [comment]
Been busy for a few days, hopefully will see this through in 1-2 days.

**Comment by maebeale** [comment]
Sounds great, @shivamvinsol!
