### ISSUE TITLE
Update README with note re login credentials

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#336]
Add note re login credentials in setup section of README.

Below the following:
```
$ bundle install
$ yarn install
$ rake dev:setup
$ heroku local -f Procfile.dev
# if you chose the local route, then you are good to go on:
  http://localhost:5000
  $ rspec (to run the test suite)
# If you chose the Docker route:
  $ docker-compose up -d -or- $ docker-compose up
  http://localhost:3000
$ rspec (to run the test suite)
```

Add:
```
View `seeds.rb` file for login email and password to use while working in development
```

**Comment by mai-am** [comment]
I can do this!

**Comment by mai-am** [comment]
> I can do this!

Sorry, I see that maybe someone already did this. I'm new to this so I hope I didn't cause any extra hassle.

**Comment by maebeale** [comment]
We've been assigning whoever adds the first comment, so best to wait after you add that you'd like to claim an issue. But, no trouble at all! Thanks for jumping in @mai-am !
