### ISSUE TITLE
Add hover text to icons on /box_requests/index.html.erb

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#343]
Please remove the following code from the index, bc we don't want that cluttering up the BoxRequests index anymore.
```
<%= box.box_items.count %> items
<%= box.aasm_state %>
```

Instead, we'd like that whenever there's an icon showing, to add hover text displaying the aasm_state.

**Comment by luchiago** [comment]
Hi. I would like to work on that

**Comment by maebeale** [comment]
Great, @luchiago !

**Comment by luchiago** [comment]
@maebeale What kind of icon? And it will be from where?
