### ISSUE TITLE
BoxAssembly React component should show inventory items from Box.box_items instead of mocks

### ISSUE THREAD

**Issue by z3ugma** [rubyforgood/voices-of-consent#354]
Make `app/javascript/src/components/box-assembly-form/BoxAssemblyForm.jsx` not pull from the `app/javascripts/mocks/mockData` in a similar vein to #353 

In `BoxDesign` you pick items to add to the box's "to-do" - all the things that should someday be put in the box (`Box.box_items`)

Once the box gets to the "package" step (`reviewed_at` and `reviewed_by_id` `!=nil`), in `BoxAssembly`, you mark the items that you've actually put into the box as you go, sort of like a packing list (Box.box_items). 

_Originally posted by @z3ugma in https://github.com/rubyforgood/voices-of-consent/pull/353_

**Comment by smoline** [comment]
I would like to work on this one @maebeale, and I have a question about it.
Do we need the option to put more than one chapstick, for instance, into the Box? Currently we show multiple of the same item in the mocks, but box_items does not have a "count" of the item in the table. 
This next question should be a separate issue, but would be an easy fix with this issue...
core_box_items are being added automatically when the box review happens, should those box_items show on the box_design form so the designer knows they have already been added?

**Comment by maebeale** [comment]
THANK YOU, @smoline !!!

Yes, the idea was to allow for more than one of any given item (there are +/- buttons). We could implement it with a quantity column (probably simplest), or by not having uniqueness on box_item and making the form count totals. I like the quantity column option -- if you do?

YES on core_box_items! They should be creating box_items that display so all the designer really has to do is approve of what's in there and maybe add or remove something. Thanks for noticing that!!!
