### ISSUE TITLE
In BoxDesign phase, only allow one of a given InventoryItem to be added to BoxItems

### ISSUE THREAD

**Issue by z3ugma** [rubyforgood/voices-of-consent#355]
Autofilter the list of available InventoryTypes that the user can "add to the box" (aka create an associated BoxItem). (Bc they can only add each InventoryType once per Box).

_Originally posted by @maebeale in https://github.com/rubyforgood/voices-of-consent/pull/353_

Update `app/javascript/src/components/box-design-form/BoxDesignForm.jsx` and related React files so that the autocomplete doesn't show an `InventoryItem` if it's already in the list of items to be added to the box in the UI

Also update Rails stuff to make sure a `Box` doesn't have multiple `BoxItems` with the same `InventoryItem`

**Comment by steph-hickman9** [comment]
Can I take this task?

**Comment by steph-hickman9** [comment]
It seems like this functionality is already implemented? When I try to add items, I can only them once. However, I can't proceed using the "the box is ready to go" button.

**Comment by maebeale** [comment]
Thank you, @steph-hickman9! Yes, you're right that it's completed. Thank you for finding this! The buttons don't work yet. That's another issue (that's claimed).
