### ISSUE TITLE
Reorder fields on /inventory_tallies/_form.html.erb

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#357]
- Move `additional_location_info` to be the last field on the `/inventory_tallies/_form.html.erb`
- Display it as a text field, rather than string

**Comment by nicpicks** [comment]
Hi, i'd like to do this as well. Can I clarify what you mean by text field though? Do you mean `text_area`? Right now, it seems like its already a string input field.

**Comment by maebeale** [comment]
@wei-tg , great! Yes, exactly. Many thanks!
