### ISSUE TITLE
Locations/_form.html.erb location_type field should default to database value

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#358]
When Editing an _existing_ Location record, the `location_type` dropdown/select field should be defaulted to the value currently in the database

Steps to reproduce:
- create a Location in the console (e.g. `Location.create!(location_type: 1, name: "New location")` )
- visit /locations index
- click "Edit" for the Location you just created
- LocationType dropdown looks empty

**Comment by sarslanoglu** [comment]
@maebeale This issue also solved by wei-tg

**Comment by MatthewBosek** [comment]
Hello, can I work on this issue?

**Comment by maebeale** [comment]
Great! Now you're assigned, @MatthewBosek . Write on slack if you have questions getting set up!

**Comment by JoaoFernandesVale** [comment]
Hi @maebeale is this still an issue?
I tried on my end and is working fine.

Steps I did:
-  Create location ( Location.create!(location_type: 1, name: "New location") )
-  Go to http://localhost:5000/locations
-  Edit the location using the UI
-  LocationType is showing the location_type: 1 as expected

<img width="1680" alt="Screenshot 2019-11-30 at 20 37 55" src="https://user-images.githubusercontent.com/27154538/69905826-6b62d600-13b1-11ea-8a43-4136123380ec.png">

<img width="1680" alt="Screenshot 2019-11-30 at 20 38 22" src="https://user-images.githubusercontent.com/27154538/69905827-71f14d80-13b1-11ea-8666-01fac48937ee.png">

<img width="1680" alt="Screenshot 2019-11-30 at 20 38 29" src="https://user-images.githubusercontent.com/27154538/69905831-79185b80-13b1-11ea-82b0-5ef2e4c0433f.png">


I noticed that we can create empty locations, perhaps there should be validations in the model to make sure that some of the location fields are present before saving

**Comment by maebeale** [comment]
Looks like we're good on this one! Yes, definitely need some validations on the model.
