### ISSUE TITLE
Fix enum bug in Locations#new

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#359]
Location has an enum called `location_type`

When going to `/locations/new`, I'm getting an error that "0" is not a valid location_type (because it's being sent via params as a string).

If I go to the `create` action in the LocationsController and replace:
```
@location = Location.new(params)
```
with:
```
params = location_params
params["location_type"] = params["location_type"].to_i
@location = Location.new(params)
```
then, it works.

The database field is an integer. The model lists the values in the key/value pairs as integers. Why/how can we make what comes in as params from the form be integers?

**Comment by nicpicks** [comment]
hi @maebeale, I'll tackle this 😃
