### ISSUE TITLE
Add second expect statement to box_request_spec.rb

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#361]
We want to verify that after `box_request.complete_review!` we get a box_request with state (aasm_state) :reviewed, and an associated box with the same state.
- Please add the following expect statement:
`expect(box_request).to have_state(:reviewed)`
above a very similar line:
`expect(box_request.box).to have_state(:reviewed)`

**Comment by marcelakopko** [comment]
PR opened here :)
https://github.com/rubyforgood/voices-of-consent/pull/366/files
