### ISSUE TITLE
Remove semicolon in expect statement

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#362]
In the box_request_spec.rb, there's the following line:
`expect(box_request.box).to have_state(:reviewed);`

Please remove the semicolon. Thank you!

**Comment by BrandonMGH** [comment]
I can do that :D

**Comment by maebeale** [comment]
Awesome, @BrandonMGH !

**Comment by BrandonMGH** [comment]
Done!

**Comment by Praful932** [comment]
Done [Pull request](https://github.com/rubyforgood/voices-of-consent/pull/369)

**Comment by iofall** [comment]
What is the status of this issue? @maebeale. Please assign it to me if it has not been fixed.

**Comment by maebeale** [comment]
@cedarfall hello! i've been waiting to hear back from folks above. please ignore this one for now. thank you tho! hopefully there's more that you might find of interest?
