### ISSUE TITLE
Typo in Box Design page

### ISSUE THREAD

**Issue by MadhuriShres** [rubyforgood/voices-of-consent#380]
**Description:**
In the design box page, once we select an item from the inventory dropdown, instructions about next steps is displayed with a thank you message. The message contains a typo where `ready` is misspelled as `read`.

Attached is the screenshot below:
<img width="1440" alt="Screen Shot 2019-10-22 at 10 45 22 PM" src="https://user-images.githubusercontent.com/10415283/67311962-38aaff80-f520-11e9-9de7-db45bd20113b.png">

**Comment by MadhuriShres** [comment]
Hi @maebeale , I would fix this typo and share the PR, if it is okay. Thanks!

**Comment by maebeale** [comment]
Good catch, @MadhuriShres ! Yes, great! Thank you!
