### ISSUE TITLE
Add new association (assembly_location) to Box

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#384]
We'll need to know the Location that the Box is being Assembled in, so we can find the correct InventoryTallies to increment and decrement. This issue is setting up the back end to handle this data.

- Add to `Box`: `belongs_to :assembly_location ...`
- Add to `Location`: `has_many :assembled_boxes ...`
- Add `assembly_location` dropdown to Box form that produces a list of Locations with type 'storage_unit'
- Add migration to connect Box to Location `add_reference :boxes, :assembly_location ...`
(look up named associations in Rails to complete the above steps)
https://edgeguides.rubyonrails.org/association_basics.html#options-for-belongs-to-foreign-key
https://www.theodinproject.com/courses/ruby-on-rails/lessons/active-record-associations

**Comment by mauricio-prl** [comment]
@maebeale Can I try to do?

**Comment by maebeale** [comment]
@m-pereira By all means! Thank you!
