### ISSUE TITLE
Add `followup_in_progress` scope to BoxRequest and to dropdown in BoxRequests index UI

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#409]
(this page should load: http://localhost:9000/box_requests?utf8=%E2%9C%93&filter_by=followup_in_progress, accessed when viewing Status, and filtering on Followup In Progress

**Comment by edwinthinks** [comment]
Opened https://github.com/rubyforgood/voices-of-consent/pull/422 to address this :). Hope it works!
