### ISSUE TITLE
Add `followed_up` to scope in box_request.rb and in dropdown on BoxRequests index UI

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#410]
(this page should load: http://localhost:9000/box_requests?utf8=%E2%9C%93&filter_by=followed_up, accessed when viewing Status, and filtering on Followed Up

**Comment by edwinthinks** [comment]
I can take a swing at this :)

**Comment by edwinthinks** [comment]
https://github.com/rubyforgood/voices-of-consent/pull/421 should address this :). 

I'll also try #409 as well as it is very similar to this one
