### ISSUE TITLE
Add end-to-end test for logged in vs logged out navbar display

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#427]
"add a test for each of the non-logged in, logged in without admin, and logged in as admin behavior? I'm thinking a test to make sure the request works end-to-end would be enough, as that would work as a regression test for what @oconnelc found" 
See this thread: https://github.com/rubyforgood/voices-of-consent/pull/414#issuecomment-591651980

**Comment by sarslanoglu** [comment]
@maebeale Fixed by this [commit](https://github.com/rubyforgood/voices-of-consent/pull/414/commits/55e6381c288f9946952886c657287bd55af333c3) in pr #414

**Comment by maebeale** [comment]
@sarslanoglu Ah! Ok! I've been travelling, so can reply to the questions, but haven't been able to review PR's. Will do some today. Thanks!
