### ISSUE TITLE
Get the tests green again

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#428]
We didn't yet have circleci and our test suite got in the red. Would LOVE help to get us green again!

**Comment by sarslanoglu** [comment]
I would love to help on this one!

**Comment by maebeale** [comment]
Woo hoo!

**Comment by maebeale** [comment]
Would love to wait for this before approving the circleci PR from @h-m-m . Thanks so much @sarslanoglu !

**Comment by sarslanoglu** [comment]
@maebeale I think @h-m-m merged his pr #420 in to develop. I can start working on it tomorrow

**Comment by maebeale** [comment]
Thanks for the offer, @sarslanoglu ! We were able to get tests green again. :)
