### ISSUE TITLE
Add callback to Location so relevant InventoryTallies get created on create

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/voices-of-consent#429]
We'd like an after_create model callback on Location (only relevant to StorageLocations) so an InventoryTally is created for that Location for every existing InventoryType in the database at a quantity of 0. This is so there's an initial ledger entry for the quantity of a specific kind of item the organization has at that Location.

**Comment by smoline** [comment]
@maebeale, are you looking for the inventory_tally only on the storage_unit location_type or on more location_types? Like not on video_chat_link, but on physical places?
```
enum location_type: {
    # Example types from ERD
    storage_unit: 0,
    shop: 1, # Can't call it `store` because it's an AR method
    meeting_space: 2,
    video_chat_link: 3,
    distribution_partner: 4,
    university: 5
}
```

**Comment by maebeale** [comment]
Hello there! THANKS for checking on this. I think only on storage_unit
right now. Do you agree?

**Comment by DouglasLutz** [comment]
Is someone working on this? If not I would like to do it.

**Comment by maebeale** [comment]
@DouglasLutz hello! will check
(@smoline hi! did you want to be assigned to this?)
